const keyMirror = require('react/lib/keyMirror');

module.exports = {

  ActionTypes: keyMirror({
    GET_BLUEPRINTS: "GET_BLUEPRINTS",
    GET_BLUEPRINTS_SUCCESS: "GET_BLUEPRINTS_SUCCESS",
    ERROR: "ERROR",
    ADD_PROCESS: "ADD_PROCESS",
	  ADD_PROCESS_SUCCESS: "ADD_PROCESS_SUCCESS",
    GET_PROCESSES: "GET_PROCESSES",
    GET_PROCESSES_SUCCESS: "GET_PROCESSES_SUCCESS",
    INDEX_PROCESS: "INDEX_PROCESS",
    SHOW_PROCESS: "SHOW_PROCESS",
    SHOW_PROCESS_SUCCESS: "SHOW_PROCESS_SUCCESS",
    RUN_PROCESS: "RUN_PROCESS",
    RUN_PROCESS_SUCCESS: "RUN_PROCESS_SUCCESS",
    OPEN_BLUEPRINT: "OPEN_BLUEPRINT",
    CLOSE_BLUEPRINT: "CLOSE_BLUEPRINT",
    ASSIGN_TASK: "ASSIGN_TASK",
    ASSIGN_TASK_SUCCESS: "ASSIGN_TASK_SUCCESS",
    FINISH_TASK: "FINISH_TASK",
    FINISH_TASK_SUCCESS: "FINISH_TASK_SUCCESS",
    GET_LOGIN_DATA: "GET_LOGIN_DATA",
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT: "LOGOUT",
    BOOTSTRAPPING_LOGIN_DATA: "BOOTSTRAPPING_LOGIN_DATA",
    BOOTSTRAPPING_BLUEPRINT_DATA: "BOOTSTRAPPING_BLUEPRINT_DATA",
    BOOTSTRAPPING_PROCESS_DATA: "BOOTSTRAPPING_PROCESS_DATA",
    CHOOSE_INPUT: "CHOOSE_INPUT",
    CHOOSE_INPUT_SUCCESS: "CHOOSE_INPUT_SUCCESS"
  }),

  ActionSources: keyMirror({
    SERVER_ACTION: null,
    VIEW_ACTION: null
  })

};
