const keyMirror = require('react/lib/keyMirror');

module.exports = {

  ActionTypes: keyMirror({
    GET_BLUEPRINTS: "GET_BLUEPRINTS",
    GET_BLUEPRINTS_SUCCESS: "GET_BLUEPRINTS_SUCCESS",
    ERROR: "ERROR",
    ADD_PROCESS: "ADD_PROCESS",
	  ADD_PROCESS_SUCCESS: "ADD_PROCESS_SUCCESS",
    GET_PROCESSES: "GET_PROCESSES",
    GET_PROCESSES_SUCCESS: "GET_PROCESSES_SUCCESS",
    INDEX_PROCESS: "INDEX_PROCESS",
    SHOW_PROCESS: "SHOW_PROCESS",
    SHOW_PROCESS_SUCCESS: "SHOW_PROCESS_SUCCESS",
    RUN_PROCESS: "RUN_PROCESS",
    RUN_PROCESS_SUCCESS: "RUN_PROCESS_SUCCESS",
    OPEN_BLUEPRINT: "OPEN_BLUEPRINT",
    CLOSE_BLUEPRINT: "CLOSE_BLUEPRINT",
  }),

  ActionSources: keyMirror({
    SERVER_ACTION: null,
    VIEW_ACTION: null
  })

};
